## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file zadaca.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_123 = Integer(123); _sage_const_120 = Integer(120); _sage_const_0 = Integer(0); _sage_const_131 = Integer(131); _sage_const_127 = Integer(127); _sage_const_125 = Integer(125); _sage_const_129 = Integer(129); _sage_const_1 = Integer(1); _sage_const_116 = Integer(116); _sage_const_136 = Integer(136)## This file (zadaca.sagetex.sage) was *autogenerated* from zadaca.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('zadaca', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_116 
_st_.blockbegin()
try:
 A = Automaton([('P', 'Q', _sage_const_0 ), ('P', 'P', _sage_const_1 ),
                 ('Q', 'P', _sage_const_1 ), ('Q', 'Q', _sage_const_0 )],
                initial_states=['P'], final_states=['Q'])
except:
 _st_.goboom(_sage_const_120 )
_st_.blockend()
_st_.current_tex_line = _sage_const_123 
_st_.blockbegin()
try:
 M = Automaton({'A': [('A', _sage_const_0 ), ('B', _sage_const_1 ), ('B', -_sage_const_1 )], 'B': [('A', _sage_const_0 )]})
except:
 _st_.goboom(_sage_const_125 )
_st_.blockend()
_st_.current_tex_line = _sage_const_127 
_st_.blockbegin()
try:
 M.state('A').is_initial = True
except:
 _st_.goboom(_sage_const_129 )
_st_.blockend()
_st_.current_tex_line = _sage_const_131 
_st_.blockbegin()
try:
 M([_sage_const_1 , -_sage_const_1 ])
 sage: False
 M([_sage_const_0 , -_sage_const_1 , _sage_const_0 , _sage_const_1 ])
 sage: True
except:
 _st_.goboom(_sage_const_136 )
_st_.blockend()
_st_.endofdoc()

